Rebrand scripts to AtriOS

diff --git a/config/files/usr/sbin/atrios-update b/config/files/usr/sbin/atrios-update
--- a/config/files/usr/sbin/atrios-update
+++ b/config/files/usr/sbin/atrios-update
@@ -14,7 +14,7 @@
 #
 # Kernel download server: https://github.com/ophub/kernel/tree/main/pub
 #
-# Command: armbian-update
+# Command: atrios-update
 #
 #========================================= Functions list =========================================
 #
@@ -37,7 +37,7 @@
 # update_deb_kernel  : Install the kernel from .deb packages
 # update_uboot       : Update the U-Boot bootloader
 # update_initrd_addr : Adjust initrd/ramdisk address for Amlogic devices
-# update_os_version  : Update the Armbian OS version string
+# update_os_version  : Update the AtriOS OS version string
 #
 # sos_kernel         : Rescue and restore the kernel to a target disk
 #
@@ -159,7 +159,7 @@ init_var() {
     FDTFILE=""
     [[ -f "/boot/uEnv.txt" ]] && { FDTFILE="$(grep -E '^FDT=.*\.dtb$' /boot/uEnv.txt | sed -E 's#.*/##' || true)"; }
     [[ -z "${FDTFILE}" && -f "/boot/extlinux/extlinux.conf" ]] && { FDTFILE="$(grep -E '/dtb/.*\.dtb$' /boot/extlinux/extlinux.conf | sed -E 's#.*/##' || true)"; }
-    [[ -z "${FDTFILE}" && -f "/boot/armbianEnv.txt" ]] && { FDTFILE="$(grep -E '^fdtfile=.*\.dtb$' /boot/armbianEnv.txt | sed -E 's#.*/##' || true)"; }
+    [[ -z "${FDTFILE}" && -f "/boot/atriosEnv.txt" ]] && { FDTFILE="$(grep -E '^fdtfile=.*\.dtb$' /boot/atriosEnv.txt | sed -E 's#.*/##' || true)"; }
     # Update FDT file records information
     [[ -n "${FDTFILE}" ]] && sed -i "s|^FDTFILE=.*|FDTFILE='${FDTFILE}'|g" ${ophub_release_file}
 
@@ -295,7 +295,7 @@ init_var() {
     check_disk
 
     # Display settings results
-    echo -e "${INFO} Armbian platform: [ ${PLATFORM} ]"
+    echo -e "${INFO} AtriOS platform: [ \${PLATFORM} ]"
     echo -e "${INFO} Current kernel: [ ${kernel_uname} ]"
     echo -e "${INFO} Kernel signature: [ ${KERNEL_SIGNATURE} ]"
     echo -e "${INFO} Kernel download type: [ ${download_type} ]"
@@ -976,11 +976,11 @@ update_initrd_addr() {
     sync && echo ""
 }
 
-# Update the Armbian OS version string
+# Update the AtriOS OS version string
 update_os_version() {
-    echo -e "${STEPS} Updating Armbian OS version..."
+    echo -e "${STEPS} Updating AtriOS OS version..."
 
-    # Get the latest Armbian OS version
+    # Get the latest AtriOS OS version
     os_version="$(
         curl -fsSL -m 15 \
             https://github.com/armbian/build/tags |
@@ -989,13 +989,13 @@ update_os_version() {
             sort -urV | head -n 1
     )"
 
-    # Update the Armbian OS version
+    # Update the AtriOS OS version
     if [[ ${?} -eq 0 && -n "${os_version}" ]]; then
-        echo -e "${INFO} The latest Armbian OS version: [ ${os_version} ]"
+        echo -e "${INFO} The latest AtriOS OS version: [ \${os_version} ]"
         sed -i "s|^VERSION=.*|VERSION=\"${os_version}\"|g" ${armbian_image_file} ${armbian_release_file}
         sed -i "s|^REVISION=.*|REVISION=\"${os_version}\"|g" ${armbian_image_file} ${armbian_release_file}
     else
-        echo -e "${PROMPT} Failed to query the latest Armbian OS version. Skipping update."
+        echo -e "${PROMPT} Failed to query the latest AtriOS OS version. Skipping update."
     fi
 
     sync && echo ""
@@ -1007,7 +1007,7 @@ sos_kernel() {
 
     # Check the current system running disk
     check_disk
-    # Supports specifying disks, such as: [ armbian-update -s mmcblk1 ]
+    # Supports specifying disks, such as: [ atrios-update -s mmcblk1 ]
     box_disk="${2}"
 
     if [[ -n "${box_disk}" ]]; then
@@ -1032,7 +1032,7 @@ sos_kernel() {
     fi
 
     rescue_disk="/dev/${box_disk}"
-    echo -e "${INFO} Armbian is running on [ /dev/${DISK_NAME} ]. Target rescue disk: [ ${rescue_disk} ]."
+    echo -e "${INFO} AtriOS is running on [ /dev/${DISK_NAME} ]. Target rescue disk: [ ${rescue_disk} ]."
 
     # Create a temporary mount directory
     umount -f ${rescue_path}/bootfs 2>/dev/null
@@ -1125,7 +1125,7 @@ help_info() {
     clear
     cat <<EOF
   ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
-  │  Example: armbian-update -k 5.15.50 -u stable                                                                                   │
+  │  Example: atrios-update -k 5.15.50 -u stable                                                                                   │
   ├───────────┬───────────────┬─────────────────────────────────────┬───────────────────────────────────────────────────────────────┤
   │  Optional │ Default       │ Value                               │ Description                                                   │
   ├───────────┼───────────────┼─────────────────────────────────────┼───────────────────────────────────────────────────────────────┤
